.TH PROJECT 1 "JULY 2009" Turnin-NG "Queen's University"
.SH PROJECT
project \- manage assignments submitted with turnin
.SH SYNOPSYS
.B project [
.I OPTIONS
.B ] [
.I project-name
.B ]
.SH DESCRIPTION
Manages assigments submitted with the
.B turnin (1)
program. Allows the creation of
courses and projects and the management of said courses and projects.

Ommitting 
.B [
.I project-name
.B ]
will cause
.B project
to use the default project.

.SH OPTIONS
.IP -\-version
Print project's version
.IP "\-h, \-\-help"
Print these options
.IP "\-d, \-\-disable"
Disables the current project.
.IP "\-e \-\-enable"
Enables submissions for the current project and make it the default project.
.IP "\-l"
Enables submissions for the current project but does not make it the default
project.
.IP "\-r, \-\-remove"
Removes the current project and all associated files.
.IP "\-i, \-\-init"
Initialize a project. Requires you to pass
.B [
.I project-name
.B ]
.IP "\-\-config=CONFIG"
Use an alternate configuration file.
.IP "\-c COURSE, \-\-switch=COURSE"
Switch between the courses you are currently administering.
.IP "\-\-create-course=COURSE"
Creates the course COURSE
.IP "\-\-delete-course=COURSE"
Deletes the course COURSE

.SH FILES
.I ~/.turnin.cf

.SH AUTHOR
Project-NG was written by Ryan Kavanagh <ryanakca@kubuntu.org> in July 2009. It
is a replacement for the 'project' and 'turnin' commands written in 1990 for the
SPARC architecture.
